#ifndef IMAGESOURCE_H
#define IMAGESOURCE_H

enum ImageSource {
    SOURCE_UNKOWN,
    SOURCE_USB,
    SOURCE_SDCARD,
    SOURCE_NETWORK,
    SOURCE_INTERNET,
    SOURCE_RNDIS,
};

#endif // IMAGESOURCE_H
